[DPE-5962] - Implement Basic TLS workflow
canonical/charmed-etcd-operator pull request #13
Opened 2024-12-17 11:21 UTC by skourta

**Still a draft!!**

This pull request introduces several changes to enable the TLS support.

### Dependency and Configuration Updates:
* Added `rustc` and `cargo` to the `charmcraft.yaml` file to support Rust dependencies.
* Updated `metadata.yaml` to include new TLS-related interfaces and requirements.
* Updated `pyproject.toml` to pin specific versions of `cryptography` and `pydantic` to ensure compatibility.

### TLS Support Enhancements:
* Introduced `TLSManager` and `TLSEvents` in `src/charm.py` to manage TLS-related operations. [[1]](diffhunk://#diff-b9ed39bbc9c0387bd3e07da31d13373745534a1cd723d3e292c73496b12e307cR14-R18) [[2]](diffhunk://#diff-b9ed39bbc9c0387bd3e07da31d13373745534a1cd723d3e292c73496b12e307cR38-R43)
* Added new properties and methods in `src/core/models.py` to handle TLS states, certificate readiness, and related URLs. [[1]](diffhunk://#diff-e46c88bb687d77b94764a732b3e08a0a7bd544a64e606429c0b787c13e1c226aR19-R28) [[2]](diffhunk://#diff-e46c88bb687d77b94764a732b3e08a0a7bd544a64e606429c0b787c13e1c226aL91-R138) [[3]](diffhunk://#diff-e46c88bb687d77b94764a732b3e08a0a7bd544a64e606429c0b787c13e1c226aL115-R157)

### Client and Command Enhancements:
* Updated `src/common/client.py` to include TLS paths and new methods for member listing and health checks. [[1]](diffhunk://#diff-f5c8dd5ff5ebd3473ee519d51e59ddb12e43e04365489c1c429256d3d20c3bc4R10-R28) [[2]](diffhunk://#diff-f5c8dd5ff5ebd3473ee519d51e59ddb12e43e04365489c1c429256d3d20c3bc4R37-R42) [[3]](diffhunk://#diff-f5c8dd5ff5ebd3473ee519d51e59ddb12e43e04365489c1c429256d3d20c3bc4R114-R116) [[4]](diffhunk://#diff-f5c8dd5ff5ebd3473ee519d51e59ddb12e43e04365489c1c429256d3d20c3bc4R135-R137) [[5]](diffhunk://#diff-f5c8dd5ff5ebd3473ee519d51e59ddb12e43e04365489c1c429256d3d20c3bc4R149-R150) [[6]](diffhunk://#diff-f5c8dd5ff5ebd3473ee519d51e59ddb12e43e04365489c1c429256d3d20c3bc4L145-R184) [[7]](diffhunk://#diff-f5c8dd5ff5ebd3473ee519d51e59ddb12e43e04365489c1c429256d3d20c3bc4R195-R239)
* Added `get_secret_from_label` method in `src/common/secrets.py` to fetch secrets by label.

### Event Handling Improvements:
* Modified `src/events/etcd.py` to defer events based on TLS readiness and peer URL availability, ensuring proper startup and configuration. [[1]](diffhunk://#diff-4d4b45129d72bf79a08e70009a59f4ebe0a016b4727117155249c864ae4a1b49R78-R117) [[2]](diffhunk://#diff-4d4b45129d72bf79a08e70009a59f4ebe0a016b4727117155249c864ae4a1b49L126-R151)

### Miscellaneous Changes:
* Added `TLSPaths` and `EtcdPaths` data classes in `src/core/workload.py` to manage TLS file paths. [[1]](diffhunk://#diff-4d1ed63ca48f694e77680b1434284f1d8d896cffe1842fb6b8b8e616c192b696R10-R64) [[2]](diffhunk://#diff-4d1ed63ca48f694e77680b1434284f1d8d896cffe1842fb6b8b8e616c192b696R88-R92)
* Updated imports and constants in various files to support the new TLS functionality. [[1]](diffhunk://#diff-728670c1b94eb83ab287f8abf7b8c88c7c80b237e1ea8a8191a942976dcb42dcL18-R24) [[2]](diffhunk://#diff-728670c1b94eb83ab287f8abf7b8c88c7c80b237e1ea8a8191a942976dcb42dcR102-R111) [[3]](diffhunk://#diff-e46c88bb687d77b94764a732b3e08a0a7bd544a64e606429c0b787c13e1c226aR8-R9)

2025-01-09 12:59 UTC, reneradoi requested changes
Hey Smail, thanks for the implementation! It looks quite good already, I have added some questions where we need to clarify things, and some remarks for things that should be changed.

One general question: Could you please add some more unit test coverage for adding a certificate/ca, e.g. via certificate availabe?

If you need clarification, we can also schedule a call to go through the topics.

Thank you!

2025-01-09 12:59 UTC, reneradoi commented on src/core/models.py
> +    TO_NO_TLS = "to-no-tls"
This could be moved to the `literals` file, there are already some `Enums` defined there.

2025-01-09 12:59 UTC, reneradoi commented on src/core/models.py
> +            cn = f"{self.unit_name}-{uuid.uuid4()!s}"
Why do we add a unique identifier to the common name?

2025-01-09 12:59 UTC, reneradoi commented on src/events/etcd.py
> +        for server in self.charm.state.servers:
I am afraid we will have to rework this section in either your or my PR, depending on which will be merged to main first :(

2025-01-09 12:59 UTC, reneradoi commented on src/events/tls.py
> +    def _on_relation_joined(self, event: RelationJoinedEvent):
I believe the logic in the handler can be removed for now, it is not really necessary to defer this event.

2025-01-09 12:59 UTC, reneradoi commented on src/events/tls.py
> +            self.charm.rolling_restart()
That means removing only one of the relations (e.g. switching the client certificate provider) would not restart the units. Is this a good idea? We would then leave the cluster in Error state forever, no?

2025-01-09 12:59 UTC, reneradoi commented on src/managers/cluster.py
> +
The `_run_etcdctl` command should only be called from the EtcdClient class. Could you please add a function `broadcast_peer_url` there and call it from the manager here (just as with the health check)?

2025-01-09 13:07 UTC, skourta commented on src/common/client.py
> +            # logger.debug(f"Running etcdctl command: {' '.join(args)}")
Will be removed. It is, yes. I thought I might leave it for future testing. It came in very handy.

2025-01-09 13:10 UTC, skourta commented on src/core/models.py
> +            cn = f"{self.unit_name}-{uuid.uuid4()!s}"
This came up in a discussion with Mykola. The `unit_name` alone might be unique in some cases like cross-model relations.

2025-01-09 13:11 UTC, skourta commented on src/events/etcd.py
> +        for server in self.charm.state.servers:
I thought as much this morning when you presented the code. Do you have a preference for how we should do it?

2025-01-09 13:17 UTC, skourta commented on src/common/client.py
> +            ).stdout
I believe it is unnecessary and should not be stripped at this point. We use the function to return multiple formats including the `json` format which returns a parseable string directly.

2025-01-09 13:22 UTC, skourta commented on src/events/tls.py
> +    def _on_relation_joined(self, event: RelationJoinedEvent):
I wanted to block the user from adding only one relation and not the other. We need both `client` and `peer` relations to be present together. This blocks the charm until they are both created.

2025-01-09 13:24 UTC, skourta commented on src/events/tls.py
> +            self.charm.rolling_restart()
My life of thinking was to enable/disable both the `client` and `peer` together we do not want a state where only one of the relations is there and the other is not.

We should further discuss this scenario.

2025-01-09 13:31 UTC, skourta commented on src/managers/cluster.py
> +
Missed this one. WIll do.

2025-01-09 15:57 UTC, reneradoi commented on src/common/client.py
> +            # logger.debug(f"Running etcdctl command: {' '.join(args)}")
I know :) If it accidentally gets activated, we print the credentials to the log. Let's rather be safe.

2025-01-09 15:58 UTC, reneradoi commented on src/common/client.py
> +            ).stdout
In an earlier PR, Mehdi explicitly asked for it: https://github.com/canonical/charmed-etcd-operator/pull/5#discussion_r1862577380

2025-01-09 16:00 UTC, reneradoi commented on src/core/models.py
> +            cn = f"{self.unit_name}-{uuid.uuid4()!s}"
Ok, I understand that. But I thought that's what the argument `add_unique_id_to_subject_name` in `generate_csr` of the tls-lib is for?

When inspecting one of the certs written to disk, I see this:
`Subject: CN = etcd/7-2403feb0-985f-4ac9-9ab3-233fe636f831, x500UniqueIdentifier = 5df60c61-6e07-4e05-8ae6-704a199f780a, O = peer`

Looks like we have to uuid's now.

2025-01-09 16:01 UTC, reneradoi commented on src/events/etcd.py
> +        for server in self.charm.state.servers:
Let's just merge changes from `main` into the respective PR after one of them has been approved+merged.

2025-01-09 16:02 UTC, reneradoi commented on src/events/tls.py
> +    def _on_relation_joined(self, event: RelationJoinedEvent):
Ok, understand. We need to document this in the user docs later.

2025-01-09 16:05 UTC, reneradoi commented on src/events/tls.py
> +            self.charm.rolling_restart()
Agree. We either need to find a way to automate replacing only one of the cert providers, or document it in the user docs how to handle this use case.

2025-01-09 16:15 UTC, reneradoi commented on src/managers/tls.py
> +                ca_path.unlink()
I've found a small issue by testing: when the `client-certificates` relation is removed, the key and ca-cert remain on disk:

```root@juju-e1b312-7:/var/snap/charmed-etcd/common/tls# ls
client.key  client_ca.pem
```
I believe this is because the `key_path` and `ca_path` variables are still set to the `peer` paths.

2025-01-10 06:06 UTC, skourta commented on src/common/client.py
> +            ).stdout
I'll add it back. Thanks, René.

2025-01-10 06:14 UTC, skourta commented on src/managers/tls.py
> +                ca_path.unlink()
Yes, that is true. I missed adding `ca_path = Path(self.workload.paths.tls.client_ca)` under the `CertType.CLIENT` condition.

2025-01-10 08:12 UTC, skourta commented on src/core/models.py
> +            cn = f"{self.unit_name}-{uuid.uuid4()!s}"
After discussing this in a meeting, we agreed to switch the common name back to the `unit_name` and leave a TODO comment to handle this in case we have cross-model relations.

2025-01-10 08:14 UTC, skourta commented on src/events/tls.py
> +            self.charm.rolling_restart()
After discussing this in a meeting, I will perform manual tests to ensure the code handles this case. The rolling restart should be initiated when the new relation is created and the new certs arrive.

2025-01-10 08:46 UTC, reneradoi commented on src/events/tls.py
> +            self.charm.rolling_restart()
I've tested it and it fails:
- juju integrate etcd:peer-certificates self-signed-certificates:certificates
- juju integrate etcd:client-certificates self-signed-certificates:certificates
- juju remove-relation etcd:client-certificates self-signed-certificates:certificates
- juju integrate etcd:client-certificates self-signed-certificates:certificates  

results in:
```
etcd/9*                      blocked   idle   12       10.105.253.156         failed to transition to/from tls state
etcd/10                      blocked   idle   10       10.105.253.228         failed to transition to/from tls state
etcd/11                      blocked   idle   11       10.105.253.70          failed to transition to/from tls state               
```

debug-log:
```
unit-etcd-11: 08:43:07 DEBUG unit.etcd/11.juju-log restart:12: Member list: None
unit-etcd-11: 08:43:07 ERROR unit.etcd/11.juju-log restart:12: Enabling TLS failed: member list command failed
unit-etcd-11: 08:43:07 ERROR unit.etcd/11.juju-log restart:12: failed to transition to/from tls state
```

2025-01-10 14:35 UTC, reneradoi commented on tests/integration/helpers.py
> +        etcd_command = f"{etcd_command} --cacert /var/snap/charmed-etcd/common/tls/client_ca.pem --cert /var/snap/charmed-etcd/common/tls/client.pem --key /var/snap/charmed-etcd/common/tls/client.key
I'm sorry Smail for bringing up another one after you already worked on all my previous comments. Could you please make this a multiline string?

```
etcd_command = f"""{etcd_command} \
                             --cacert ... \
                             --cert ... \
...
```
That would make it easier to read.

2025-01-11 21:40 UTC, Mehdi-Bendriss requested changes
Thanks Smail, great work! I left some comments and some questions

2025-01-11 21:40 UTC, Mehdi-Bendriss commented on tests/integration/test_tls.py
> +    await ops_test.model.wait_for_idle(apps=[APP_NAME], status="active", timeout=1000)
In another PR - Please move away from `wait_for_idle` in favor of [`wait_until`](https://github.com/canonical/opensearch-operator/blob/2/edge/tests/integration/helpers_deployments.py#L348). This will give us more fine grained control over the app + unit statuses.

2025-01-11 21:40 UTC, Mehdi-Bendriss commented on tests/integration/test_tls.py
> +    endpoints = get_cluster_endpoints(ops_test, APP_NAME, tls_enabled=True)
From this line onwards extract it in ots own separate test

2025-01-11 21:40 UTC, Mehdi-Bendriss commented on tests/integration/test_tls.py
> +async def test_turning_off_tls(ops_test: OpsTest) -> None:
```suggestion
async def test_disable_tls(ops_test: OpsTest) -> None:
```

2025-01-11 21:40 UTC, Mehdi-Bendriss commented on tests/integration/test_tls.py
> +    assert model is not None
I don't think this is needed.

2025-01-11 21:40 UTC, Mehdi-Bendriss commented on tests/integration/test_tls.py
> +    await etcd_app.remove_relation("client-certificates", f"{TLS_NAME}:certificates")
depending on whether we require both TLS relations to be established or not for TLS to be enabled in a cluster before removing this relation, let's add a test on the application status and confirm that the status was changed accordingly.

2025-01-11 21:40 UTC, Mehdi-Bendriss commented on tests/integration/test_tls.py
> +    )
add a new .put (different key/value and assert on it)

2025-01-11 21:40 UTC, Mehdi-Bendriss commented on tests/integration/test_tls.py
> +async def test_turning_on_tls(ops_test: OpsTest) -> None:
```suggestion
async def test_enable_tls(ops_test: OpsTest) -> None:
```

2025-01-11 21:40 UTC, Mehdi-Bendriss commented on tests/integration/test_tls.py
> +    assert model is not None
Similar comment, is this needed?

2025-01-11 21:40 UTC, Mehdi-Bendriss commented on tests/integration/test_tls.py
> +    await ops_test.model.integrate(f"{APP_NAME}:client-certificates", TLS_NAME)
similar comment on status

2025-01-11 21:40 UTC, Mehdi-Bendriss commented on tests/integration/test_tls.py
> +    )
needs a `.put` here

2025-01-13 05:27 UTC, skourta commented on src/charm.py
> +                logger.debug("Broadcasting new peer url")
Understood.

2025-01-13 05:29 UTC, skourta commented on src/charm.py
> +                self.tls_manager.set_tls_state(state=TLSState.TLS)
I wanted to keep all code and logic related to TLS in the manager and event files except for what is necessary. I can directly move this to the `charm.py` but prefer to move it to the `EtcdServer` instead. WDYT?

2025-01-13 05:34 UTC, skourta commented on src/charm.py
> +                    self.state.unit_server.peer_url.replace("http://", "https://")
The `peer_url` is a property and will be recomputed thus will stay up-to-date based on whether we succeeded in enabling/disabling TLS. I added the argument to the `broadcast_peer_url` because you will broadcast the opposite in terms of HTTP/HTTPS to what you are currently running but I think we can do the logic inside the function as well. With the argument I find it more expressive on the calling level as you will know directly what you are broadcasting without going into the function and checking the code and state of the TLS.

2025-01-13 05:36 UTC, skourta commented on src/charm.py
> +    def _restart(self, _) -> None:
- we do not want to update the state of the TLS unless it has successfully been updated because we rely on that state to build the config and other properties. We also will be using the `_restart` function outside of TLS.

2025-01-13 05:40 UTC, skourta commented on src/events/tls.py
> +    def _on_relation_joined(self, event: RelationJoinedEvent):
That is just what we decided on when I was working on the spec. It is documented in the spec.

2025-01-13 05:42 UTC, skourta commented on tests/integration/test_tls.py
> +    assert model is not None
This is mostly because the API of juju returns `Model | None`asserting that the model is not `None` enforces the type to be `Model` only. It is the same for all other assertions of this type.

2025-01-13 05:44 UTC, skourta commented on src/charm.py
> +    def rolling_restart(self) -> None:
Yes, it is. The idea is to abstract away the need to import and use the `RESTART_RELATION` literal and the technicality of the `rolling_restart`. If we decide to change the rolling restart mechanism in the future we would only have to change the logic here.

2025-01-13 05:47 UTC, skourta commented on src/common/client.py
> +        cluster_arg: bool = False,
I have discussed this before with @reneradoi and this was the agreed-upon approach to use. I'm open to changing this but I think it would be better handled in an independent PR because we will change not only what I added but all of the arguments.

2025-01-13 05:49 UTC, skourta commented on src/common/client.py
> +                args.append(f"--cacert={TLS_ROOT_DIR}/client_ca.pem")
They are needed to bypass the check done by etcd that the user provided certs. If we do not provide certs the request will be rejected directly.

2025-01-13 05:52 UTC, skourta commented on src/core/models.py
> +        return self.relation_data.get("peer-cert-ready", "") == "True"
Yes, I am certain of the capital `T` I explicitly tested it and `str(True)` is `"True"`. I also checked the content of the data bag just to make sure. I am ok with changing it to lowercase all the time as well.

2025-01-13 05:55 UTC, skourta commented on src/events/tls.py
> +            raise Exception("Missing certificate or private key")
This is preventative only as they should always be returned by the lib. In case it fails I want the hook to be reexcuted hence raising the `Exception`. Please let me know if this is wrong and needs to be changed.

2025-01-13 05:56 UTC, skourta commented on src/events/tls.py
> +        if not cert or not private_key:
This is preventative only as mentioned in the other comment.

2025-01-13 05:58 UTC, skourta commented on src/events/tls.py
> +        self.charm.set_status(Status.TLS_NOT_READY)
Yes, this is something I want to change. I talked to René about this just last Friday. We have some competing logic for setting the status. I need to further document how to prevent this and figure out a better way to set the statuses.
I will implement what you described in 1.

2025-01-13 07:21 UTC, skourta commented on src/events/etcd.py
> +            self.charm.state.cluster.update({"initial-cluster-state": "existing"})
I believe this should be fixed in a future PR to handle both my uses and @reneradoi .
WDYT?

2025-01-13 07:23 UTC, skourta commented on src/common/client.py
> +            }
Does this also apply to event handlers?

2025-01-13 07:25 UTC, skourta commented on src/events/tls.py
> +                    organization=CertType.PEER.value,
The `host_mapping`?

2025-01-13 08:09 UTC, skourta commented on src/managers/tls.py
> +                certificate_path = Path(self.workload.paths.tls.peer_cert)
@reneradoi WDYT?

2025-01-13 08:30 UTC, skourta commented on tests/integration/test_tls.py
> +    await etcd_app.remove_relation("client-certificates", f"{TLS_NAME}:certificates")
There is a unit test to test for that. Should add an integration test as well?

2025-01-13 08:50 UTC, reneradoi commented on src/managers/tls.py
> +                certificate_path = Path(self.workload.paths.tls.peer_cert)
I know you like to manage files as Paths, but I'd rather keep it simple (as simple as possible):
- treat the file paths as str
- have a method in `workload.py` to remove a file (similar to `write_file()`)
- call for example `workload.remove_file(certificate_path)` from the TLS manager

This would also allow for better separation of concerns by delegating the file operations to the workload (currently the TLS manager is doing file operations which is anti-pattern).

As for the `if/else` instead of `match/case`: agree, `if/else` is fine as we only have two cases to distinguish here.

2025-01-13 10:13 UTC, skourta commented on src/managers/tls.py
> +        """Set the certificate status.
Changed name to state. By using a getter and a setter we abstract away the key of the data. In case we want to change (which coincidentally I need to do) it would be changed in one place.

2025-01-13 12:42 UTC, skourta commented on src/events/tls.py
> +            self.charm.rolling_restart()
This needs to be handled regardless. Removing a relation and re-adding it is how a user can rotate certificates manually. I'm working on it.

2025-01-16 13:55 UTC, Mehdi-Bendriss commented on src/events/tls.py
> +                    organization=CertType.PEER.value,
@skourta the `organization`

2025-01-16 13:58 UTC, Mehdi-Bendriss commented on tests/integration/test_tls.py
> +    await etcd_app.remove_relation("client-certificates", f"{TLS_NAME}:certificates")
@skourta not a full integration test, but a line checking on the current status in the integration test logic following these removals

2025-01-16 14:07 UTC, skourta commented on tests/integration/test_tls.py
> +    await etcd_app.remove_relation("client-certificates", f"{TLS_NAME}:certificates")
Isn't that handled by the `wait_for_idle` with status `active`?

2025-01-16 14:10 UTC, skourta commented on src/events/tls.py
> +                    organization=CertType.PEER.value,
I had to use a field on the certificate to know from which relation the certificate comes. I chose `organization` arbitrarily because it is not used in the TLS library and we do not use it. When we receive the certificate in a `CertificateAvailable` event all we have is the certificate and its info.

2025-01-17 05:33 UTC, skourta commented
> Hey @skourta when testing with just one unit and only the peer-certificates relation, the `peer-certificates-relation-created` hook fails:
> 
> ```
> $ juju status
> Model  Controller      Cloud/Region         Version  SLA          Timestamp
> etcd   dev-controller  localhost/localhost  3.6.0    unsupported  15:18:23Z
> 
> App                       Version  Status  Scale  Charm                     Channel        Rev  Exposed  Message
> etcd                               error       1  charmed-etcd                              12  no       hook failed: "peer-certificates-relation-created"
> self-signed-certificates           active      1  self-signed-certificates  latest/stable  155  no       
> 
> Unit                         Workload  Agent  Machine  Public address  Ports  Message
> etcd/30*                     error     idle   36       10.105.253.26          hook failed: "peer-certificates-relation-created"
> self-signed-certificates/2*  active    idle   35       10.105.253.23          
> 
> $ juju debug-log
> unit-etcd-30: 15:17:42 DEBUG unit.etcd/30.juju-log peer-certificates:28: Emitting Juju event peer_certificates_relation_created.
> unit-etcd-30: 15:17:42 INFO unit.etcd/30.juju-log peer-certificates:28: Private key generated
> unit-etcd-30: 15:17:42 ERROR unit.etcd/30.juju-log peer-certificates:28: Uncaught exception while in charm code:
> Traceback (most recent call last):
>   File "/var/lib/juju/agents/unit-etcd-30/charm/./src/charm.py", line 170, in <module>
>     ops.main(EtcdOperatorCharm)  # type: ignore
>   File "/var/lib/juju/agents/unit-etcd-30/charm/venv/ops/__init__.py", line 343, in __call__
>     return _main.main(charm_class=charm_class, use_juju_for_storage=use_juju_for_storage)
>   File "/var/lib/juju/agents/unit-etcd-30/charm/venv/ops/_main.py", line 543, in main
>     manager.run()
>   File "/var/lib/juju/agents/unit-etcd-30/charm/venv/ops/_main.py", line 529, in run
>     self._emit()
>   File "/var/lib/juju/agents/unit-etcd-30/charm/venv/ops/_main.py", line 518, in _emit
>     _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
>   File "/var/lib/juju/agents/unit-etcd-30/charm/venv/ops/_main.py", line 134, in _emit_charm_event
>     event_to_emit.emit(*args, **kwargs)
>   File "/var/lib/juju/agents/unit-etcd-30/charm/venv/ops/framework.py", line 347, in emit
>     framework._emit(event)
>   File "/var/lib/juju/agents/unit-etcd-30/charm/venv/ops/framework.py", line 857, in _emit
>     self._reemit(event_path)
>   File "/var/lib/juju/agents/unit-etcd-30/charm/venv/ops/framework.py", line 947, in _reemit
>     custom_handler(event)
>   File "/var/lib/juju/agents/unit-etcd-30/charm/lib/charms/tls_certificates_interface/v4/tls_certificates.py", line 1024, in _configure
>     self._send_certificate_requests()
>   File "/var/lib/juju/agents/unit-etcd-30/charm/lib/charms/tls_certificates_interface/v4/tls_certificates.py", line 1273, in _send_certificate_requests
>     if not self._certificate_requested(certificate_request):
>   File "/var/lib/juju/agents/unit-etcd-30/charm/lib/charms/tls_certificates_interface/v4/tls_certificates.py", line 1170, in _certificate_requested
>     csr = self._certificate_requested_for_attributes(certificate_request)
>   File "/var/lib/juju/agents/unit-etcd-30/charm/lib/charms/tls_certificates_interface/v4/tls_certificates.py", line 1181, in _certificate_requested_for_attributes
>     for requirer_csr in self.get_csrs_from_requirer_relation_data():
>   File "/var/lib/juju/agents/unit-etcd-30/charm/lib/charms/tls_certificates_interface/v4/tls_certificates.py", line 1200, in get_csrs_from_requirer_relation_data
>     requirer_relation_data = _RequirerData.load(relation.data[app_or_unit])
>   File "/var/lib/juju/agents/unit-etcd-30/charm/lib/charms/tls_certificates_interface/v4/tls_certificates.py", line 87, in load
>     nest_under = cls.model_config.get("_NEST_UNDER")
> AttributeError: type object '_RequirerData' has no attribute 'model_config'
> ```
> 
> I'm not sure yet what's wrong. It can be reproduced, I've tried now a couple of times already. Could you please test this setup as well and see if you can reproduce this error?

I cannot seem to reproduce this error. What is even weirder is that it is coming from the TLS library.

I tried with `peer-certificates` enabled on cluster set up and also to enable it after the cluster starts.

2025-01-17 11:27 UTC, reneradoi commented
The previously reported error is not related to the PR. I had to `charmcraft clean` my local environment to get the new required version of `pydantic` installed into the charm I built locally. Before doing that, `charmcraft pack` always installed `pydantic 1.10`.

2025-01-17 13:02 UTC, reneradoi requested changes
Hey Smail, it's already looking quite good! I have put some small things to adjust, but there is one logical issue that we need to think about again. It's related to adding units when TLS is enabled. Maybe we should also add an integration test for this.

2025-01-17 13:35 UTC, skourta commented on src/events/etcd.py
> +        ):
In the last point, the event will not be deferred again because the `tls_state` will be set to `TLS`. Once the hook executing `certificate_available` event is over the data bag is saved and the start can go on normally.

The bug is present but is in the `add_member` function as it always adds the `peer_url` as if there is no TLS. When the peer relation joined event is triggered, the peer_url is in http:// format because the node would still not have gotten its certificates.

I also discovered a bug. When you remove a unit it does not update the `cluster_members` in the data bag.

2025-01-17 14:11 UTC, reneradoi commented on src/events/etcd.py
> +        ):
I'll retest, thanks for the analysis and quick fix!

Regarding
> When you remove a unit it does not update the cluster_members in the data bag
That is true, because scale-down is not implemented yet.

2025-01-17 14:40 UTC, reneradoi commented on src/events/etcd.py
> +        ):
My manual tests are fine now, adding units in different kind of constellations (both TLS relations, only peer or only client certs) works perfectly. Thanks for the fix!

2025-01-17 14:52 UTC, reneradoi approved these changes
Really great job here Smail!

2025-01-17 19:16 UTC, Mehdi-Bendriss reviewed
Excellent work Smail! It looks very clean! 
I left some comments / questions as well as the discussion points that are still relevant from the previous round.

2025-01-17 19:16 UTC, Mehdi-Bendriss commented on src/events/tls.py
> +            logger.debug("Rotating client certificates")
similar question, on not requiring a restart?

2025-01-17 19:16 UTC, Mehdi-Bendriss commented on tests/integration/test_tls.py
> +    await etcd_app.remove_relation("client-certificates", f"{TLS_NAME}:certificates")
No - this was a reference to the initial implementation where removing 1 TLS relation would put the charm in a blocked state, until the second relation is removed.
This is no longer relevant, as we're no longer mandating the 0 - 2 relations.

2025-01-17 19:16 UTC, Mehdi-Bendriss commented on tests/integration/test_tls.py
> +    assert model is not None, "Model is not set"
You're already asserting on it in the previous test `test_build_and_deploy_with_tls`.
we can remove this here and in all subsequent tests

2025-01-17 19:16 UTC, Mehdi-Bendriss commented on tests/integration/test_tls.py
> +async def test_disable_tls(ops_test: OpsTest) -> None:
Missing docstring -- please add a relevant docstring for every subsequent test

2025-01-17 19:16 UTC, Mehdi-Bendriss commented on tests/integration/test_tls.py
> +        assert cluster_member["peerURLs"][0].startswith("http://"), "Peer URL is not http"
nice

2025-01-17 19:18 UTC, Mehdi-Bendriss commented on src/events/tls.py
> +            raise Exception("Missing certificate or private key")
In that case, we should not test against and raise, since it will crash anyway if they're "somehow" missing by the lib
we should assume they're always returned

2025-01-17 19:22 UTC, Mehdi-Bendriss commented on src/managers/tls.py
> +        """Set the certificate status.
That's fine, but we should ideally not change the keys starting from when we first go to stable - remember the upgrade issues when dealing with non-backward compatible relation keys

2025-01-17 19:26 UTC, Mehdi-Bendriss commented on src/workload.py
> +            logger.exception(str(e))
This comment is still relevant: 
1. the `start` method fails silently 
2. the exception raised by `restart` is not handled by `restart_member` which returns a `bool`

2025-01-17 19:29 UTC, Mehdi-Bendriss commented on src/core/models.py
> +    def http(self) -> str:
still relevant

2025-01-20 04:36 UTC, skourta commented on src/core/models.py
> +    def http(self) -> str:
GitHub seems to be showing the code version when the comment was written as this suggestion has been applied in the newest code.

2025-01-20 04:37 UTC, skourta commented on src/events/tls.py
> +        self.framework.observe(
Likewise, updated but GitHub still shows the old code version.

2025-01-20 04:41 UTC, skourta commented on src/events/tls.py
> +            raise Exception("Missing certificate or private key")
The lib still has a return type of `Certiciate | None` so it will not fail in that case and will just return None.
This also forces the correct type and removes linting errors.

2025-01-20 04:44 UTC, skourta commented on src/workload.py
> +            logger.exception(str(e))
Fixed and GitHub showing outdated code.

2025-01-20 04:47 UTC, skourta commented on src/events/tls.py
> +            logger.debug("Rotating peer certificates")
Updating certificates does not require a restart. etcd picks up the certs from disk every time there's a request. All we have to do is update the certs on disk. This is also mentioned in the spec.

2025-01-20 04:53 UTC, skourta commented on src/common/client.py
> +                id=str(hex(member["ID"]))[2:],
Because when you convert to a hex it will start with `0x`

2025-01-20 04:55 UTC, skourta commented on src/core/models.py
> +        scheme = "https" if self.tls_peer_state in [TLSState.TLS, TLSState.TO_NO_TLS] else "http"
That is how I initially coded it, but we would have 2 properties: one for peer and one for client. Since this is the only place they are used, I removed them and set them as variables.
LMWYT

2025-01-20 04:56 UTC, skourta commented on src/events/etcd.py
> +        if (
This checks that we are not currently transitioning TLS state. We should only start when TLS is ready or when there is no TLS. If there's a transition the `tls_state` will be set to `TO_TLS` or to `TO_NO_TLS`.

2025-01-20 05:00 UTC, skourta commented on src/events/tls.py
> +            logger.debug("Rotating client certificates")
Updating certificates does not require a restart. etcd picks up the certs from disk every time there's a request. All we have to do is update the certs on disk. This is also mentioned in the spec.

Updating CA on the other hand will need a restart.

2025-01-20 05:30 UTC, skourta commented on src/charm.py
> +    def _restart_disable_peer_tls(self, _) -> None:
We can do that. The only downside is that the function will need to have some logic to decide which function to execute. That knowledge is currently abstracted by setting the name of the function rolling ops would execute directly.

2025-01-20 08:36 UTC, Mehdi-Bendriss commented on src/common/client.py
> +                id=str(hex(member["ID"]))[2:],
why should it be converted to a hex? why not take the member["ID"] as is?

2025-01-20 08:46 UTC, reneradoi commented on src/common/client.py
> +                id=str(hex(member["ID"]))[2:],
`etcdctl` requires the member id to be given as hex. I've had the same problem [here](https://github.com/canonical/charmed-etcd-operator/blob/main/src/common/client.py#L119-L121).

2025-01-21 04:55 UTC, skourta commented on src/events/tls.py
> +            raise Exception("Missing certificate or private key")
I caught the TLS v4 lib bug using this check, and I suggest we keep it.

2025-01-21 04:55 UTC, skourta commented on src/events/tls.py
> +        if not cert or not private_key:
I caught the TLS v4 lib bug using this check, and I suggest we keep it.

2025-01-21 04:56 UTC, skourta commented on src/managers/config.py
> +                "https://", "http://"
You mean have both http and https versions as properties and choose one based on the state of tls?

2025-01-22 07:14 UTC, Mehdi-Bendriss approved these changes

2025-01-22 07:35 UTC, reneradoi approved these changes

2025-01-22 07:50 UTC, merged